modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="dreams_and_nightmares"
version="0.2.0"
displayName="Dreams and Nightmares"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Emeraldnickel"

[[dependencies.dreams_and_nightmares]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




